env:
  global:
    - DEST_DIR="build"
    - NODE_ENV="production"

language: node_js
node_js:
  - "6"

before-install: npm install -g grunt-cli
script: scripts/build.sh

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
