language: node_js
node_js:
  - "6"

env:
  global:
    - DEST_DIR="build"
    - NODE_ENV="production"

before_install: npm install -g grunt-cli
script: grunt

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
