env:
  global:
    - DEST_DIR="build"
    - NODE_ENV="production"

language: node_js
node_js:
  - "5"

before_install: npm install -g grunt-cli
install: npm install
script: grunt

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
